package(default_visibility = ["//visibility:public"])

cc_library(
	name = "BlueFramework.Core",
	srcs = [
        "src/BlueFramework/Core/namespace.h",
		"src/BlueFramework/Core/Uri.cpp",
		"src/BlueFramework/Core/Uri.h"
	],
	includes = ["src"],
)