cc_test(
    name = "UriTest",
    srcs = [
		"UriTest.cpp",
	],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@googletest//:gtest_main",
        "//Core:BlueFramework.Core",
    ],
)